version: "3.8"

services:
  redis:
    image: ghcr.io/aut-cloud-computing-fall-2024/redis
    container_name: redis
    networks:
      - hw2-network
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data 

  api:
    image: api:latest
    container_name: api
    depends_on:
      - redis
    networks:
      - hw2-network
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis  
      - REDIS_PORT=6379  

networks:
  hw2-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
