apiVersion: v1
kind: Service
metadata:
  name: redis # Service name (used by your app to connect)
  labels:
    app: redis
spec:
  selector:
    app: redis # Matches the label of the Redis pods
  ports:
    - protocol: TCP
      port: 6379        # Port exposed by the service
      targetPort: 6379  # Port Redis is listening on in the pod
  type: ClusterIP       # Exposes the service within the cluster
